"""First migration

Revision ID: 3920bd4578e9
Revises: 
Create Date: 2022-10-03 19:51:51.330596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3920bd4578e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('making_time', sa.String(), nullable=True),
    sa.Column('serves', sa.String(), nullable=True),
    sa.Column('ingredients', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipses_cost'), 'recipses', ['cost'], unique=False)
    op.create_index(op.f('ix_recipses_created_at'), 'recipses', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipses_id'), 'recipses', ['id'], unique=False)
    op.create_index(op.f('ix_recipses_ingredients'), 'recipses', ['ingredients'], unique=False)
    op.create_index(op.f('ix_recipses_making_time'), 'recipses', ['making_time'], unique=False)
    op.create_index(op.f('ix_recipses_serves'), 'recipses', ['serves'], unique=False)
    op.create_index(op.f('ix_recipses_title'), 'recipses', ['title'], unique=False)
    op.create_index(op.f('ix_recipses_updated_at'), 'recipses', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_description'), 'items', ['description'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_description'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recipses_updated_at'), table_name='recipses')
    op.drop_index(op.f('ix_recipses_title'), table_name='recipses')
    op.drop_index(op.f('ix_recipses_serves'), table_name='recipses')
    op.drop_index(op.f('ix_recipses_making_time'), table_name='recipses')
    op.drop_index(op.f('ix_recipses_ingredients'), table_name='recipses')
    op.drop_index(op.f('ix_recipses_id'), table_name='recipses')
    op.drop_index(op.f('ix_recipses_created_at'), table_name='recipses')
    op.drop_index(op.f('ix_recipses_cost'), table_name='recipses')
    op.drop_table('recipses')
    # ### end Alembic commands ###
